"""HS256 JWT issue + verify for audio-relay browser sessions.

Lives in ``shared/`` so the web service issues and the audio-relay
verifies using the same code — schema drift between the two would
silently break every browser → audio path.

Wire format follows RFC 7519 with the following claims pinned:

  iss        ``"openring-web"``
  aud        ``"openring-audio"``
  sub        admin username
  device_id  the device the browser intends to talk to
  jti        random one-shot identifier
  iat / exp  unix seconds; default lifetime 5 minutes

The signing key is base64-encoded 32+ bytes loaded from
``OPENRING_AUDIO_KEY``.  Generated by ``setup.sh`` on first run; not
shared with the existing ``DETECTION_HMAC_KEY`` (different protection
scope, different rotation cadence).
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import logging
import os
import time
from dataclasses import dataclass

logger = logging.getLogger(__name__)

ENV_VAR = "OPENRING_AUDIO_KEY"
DEFAULT_LIFETIME_SECONDS = 300
EXPECTED_ISSUER = "openring-web"
EXPECTED_AUDIENCE = "openring-audio"


# ── Errors ───────────────────────────────────────────────────────────


class JwtError(ValueError):
    """Raised when a JWT can't be verified."""


# ── Key handling ─────────────────────────────────────────────────────


def load_key_from_env(var_name: str = ENV_VAR) -> bytes | None:
    """Decode the base64-encoded HS256 signing key from the env.

    Returns None when the var is unset or invalid — caller refuses
    browser sessions in that case (Pi sessions don't depend on this
    key).
    """
    raw = os.environ.get(var_name, "").strip()
    if not raw:
        return None
    try:
        key = base64.b64decode(raw, validate=True)
    except Exception:
        logger.error("%s is set but not valid base64 — treating as absent", var_name)
        return None
    if len(key) < 16:
        logger.error("%s decodes to %d bytes (need >= 16)", var_name, len(key))
        return None
    return key


# ── Sign + verify ────────────────────────────────────────────────────


def _b64url_decode(data: str) -> bytes:
    pad = "=" * (-len(data) % 4)
    return base64.urlsafe_b64decode(data + pad)


def _b64url_encode(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


@dataclass(frozen=True)
class AudioJwt:
    sub: str
    device_id: str
    jti: str
    exp: int


def issue(
    key: bytes,
    *,
    sub: str,
    device_id: str,
    jti: str,
    lifetime_seconds: int = DEFAULT_LIFETIME_SECONDS,
    now: int | None = None,
) -> str:
    """Issue an HS256-signed JWT for an audio session."""
    if not sub or not device_id or not jti:
        raise ValueError("sub / device_id / jti are required")
    iat = now if now is not None else int(time.time())
    payload = {
        "iss": EXPECTED_ISSUER,
        "aud": EXPECTED_AUDIENCE,
        "sub": sub,
        "device_id": device_id,
        "jti": jti,
        "iat": iat,
        "exp": iat + lifetime_seconds,
    }
    header = {"alg": "HS256", "typ": "JWT"}
    h = _b64url_encode(json.dumps(header, separators=(",", ":")).encode())
    p = _b64url_encode(json.dumps(payload, separators=(",", ":")).encode())
    signing_input = f"{h}.{p}".encode()
    sig = hmac.new(key, signing_input, hashlib.sha256).digest()
    s = _b64url_encode(sig)
    return f"{h}.{p}.{s}"


def verify(
    raw_jwt: str,
    key: bytes,
    *,
    now: int | None = None,
    leeway_seconds: int = 5,
) -> AudioJwt:
    """Verify an HS256 JWT.  Raises JwtError on any failure.

    5-second leeway tolerates small clock drift between web and
    audio-relay containers.
    """
    if not raw_jwt or raw_jwt.count(".") != 2:
        raise JwtError("token is not three dot-separated parts")
    h_b64, p_b64, s_b64 = raw_jwt.split(".")
    try:
        header = json.loads(_b64url_decode(h_b64))
        payload = json.loads(_b64url_decode(p_b64))
        sig = _b64url_decode(s_b64)
    except Exception as exc:
        raise JwtError(f"token is not valid JWT: {exc}") from exc

    if header.get("alg") != "HS256":
        raise JwtError(f"unexpected alg {header.get('alg')!r}")
    if header.get("typ") not in (None, "JWT"):
        raise JwtError(f"unexpected typ {header.get('typ')!r}")

    expected_sig = hmac.new(key, f"{h_b64}.{p_b64}".encode(), hashlib.sha256).digest()
    if not hmac.compare_digest(sig, expected_sig):
        raise JwtError("signature mismatch")

    if payload.get("iss") != EXPECTED_ISSUER:
        raise JwtError(f"unexpected iss {payload.get('iss')!r}")
    if payload.get("aud") != EXPECTED_AUDIENCE:
        raise JwtError(f"unexpected aud {payload.get('aud')!r}")

    sub = payload.get("sub")
    device_id = payload.get("device_id")
    jti = payload.get("jti")
    exp = payload.get("exp")
    if not isinstance(sub, str) or not sub:
        raise JwtError("missing sub claim")
    if not isinstance(device_id, str) or not device_id:
        raise JwtError("missing device_id claim")
    if not isinstance(jti, str) or not jti:
        raise JwtError("missing jti claim")
    if not isinstance(exp, int):
        raise JwtError("missing or non-integer exp claim")

    current = now if now is not None else int(time.time())
    if exp + leeway_seconds < current:
        raise JwtError(f"token expired (exp={exp}, now={current})")

    return AudioJwt(sub=sub, device_id=device_id, jti=jti, exp=exp)
