"""JWT verification for browser → audio-relay sessions.

The web service issues HS256-signed JWTs from ``OPENRING_AUDIO_KEY``
and the audio-relay verifies on connect.  Single-use enforcement
via the ``jti`` claim — the relay keeps an in-memory set of used
jtis so a captured token can be replayed at most once before
expiry.

Pi-side connections use the existing device Bearer token from
``services/web/src/auth.py:validate_device_token``; that path lives
in ``main.py`` because it requires a SQLite connection and we
want this module to stay dependency-free.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import logging
import os
import threading
import time
from dataclasses import dataclass

logger = logging.getLogger(__name__)

# Same env-var pattern as DETECTION_HMAC_KEY (`shared/event_signing.py`).
# Generated by ``setup.sh`` and distributed via the host's ``.env``.
ENV_VAR = "OPENRING_AUDIO_KEY"

DEFAULT_LIFETIME_SECONDS = 300  # 5 minutes — matches docs/AUDIO.md
EXPECTED_ISSUER = "openring-web"
EXPECTED_AUDIENCE = "openring-audio"


# ── Errors ───────────────────────────────────────────────────────────


class JwtError(ValueError):
    """Raised when a JWT can't be verified.  Caller usually responds
    with ``ErrorCode.AUTH`` and closes."""


# ── Key handling ─────────────────────────────────────────────────────


def load_key_from_env(var_name: str = ENV_VAR) -> bytes | None:
    """Decode the base64-encoded HS256 signing key from the env.

    Returns None when the env var is unset or invalid — the caller
    should refuse browser sessions in that case (Pi sessions still
    work because they don't depend on this key)."""
    raw = os.environ.get(var_name, "").strip()
    if not raw:
        return None
    try:
        key = base64.b64decode(raw, validate=True)
    except Exception:
        logger.error("%s is set but not valid base64 — treating as absent", var_name)
        return None
    if len(key) < 16:
        logger.error("%s decodes to %d bytes (need >= 16)", var_name, len(key))
        return None
    return key


# ── Sign + verify ────────────────────────────────────────────────────


def _b64url_decode(data: str) -> bytes:
    """RFC 7515 §3 base64url, with padding restoration."""
    pad = "=" * (-len(data) % 4)
    return base64.urlsafe_b64decode(data + pad)


def _b64url_encode(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


@dataclass(frozen=True)
class AudioJwt:
    """Validated audio-session JWT claims.  All fields required."""

    sub: str            # admin username
    device_id: str
    jti: str
    exp: int            # unix seconds


def issue(
    key: bytes,
    *,
    sub: str,
    device_id: str,
    jti: str,
    lifetime_seconds: int = DEFAULT_LIFETIME_SECONDS,
    now: int | None = None,
) -> str:
    """Issue an HS256-signed JWT for an audio session.

    Used by the web service when the browser POSTs
    ``/api/audio/session``.  The audio-relay only verifies; it never
    issues."""
    if not sub or not device_id or not jti:
        raise ValueError("sub / device_id / jti are required")
    iat = now if now is not None else int(time.time())
    payload = {
        "iss": EXPECTED_ISSUER,
        "aud": EXPECTED_AUDIENCE,
        "sub": sub,
        "device_id": device_id,
        "jti": jti,
        "iat": iat,
        "exp": iat + lifetime_seconds,
    }
    header = {"alg": "HS256", "typ": "JWT"}
    h = _b64url_encode(json.dumps(header, separators=(",", ":")).encode())
    p = _b64url_encode(json.dumps(payload, separators=(",", ":")).encode())
    signing_input = f"{h}.{p}".encode()
    sig = hmac.new(key, signing_input, hashlib.sha256).digest()
    s = _b64url_encode(sig)
    return f"{h}.{p}.{s}"


def verify(
    raw_jwt: str,
    key: bytes,
    *,
    now: int | None = None,
    leeway_seconds: int = 5,
) -> AudioJwt:
    """Verify an HS256 JWT.  Raises ``JwtError`` on any failure.

    Leeway of 5 seconds tolerates small clock drift between web and
    audio-relay containers (both run on the same host but Docker's
    PID-namespaced clocks drift sometimes)."""
    if not raw_jwt or raw_jwt.count(".") != 2:
        raise JwtError("token is not three dot-separated parts")
    h_b64, p_b64, s_b64 = raw_jwt.split(".")
    try:
        header = json.loads(_b64url_decode(h_b64))
        payload = json.loads(_b64url_decode(p_b64))
        sig = _b64url_decode(s_b64)
    except Exception as exc:
        raise JwtError(f"token is not valid JWT: {exc}") from exc

    if header.get("alg") != "HS256":
        raise JwtError(f"unexpected alg {header.get('alg')!r}")
    if header.get("typ") not in (None, "JWT"):
        raise JwtError(f"unexpected typ {header.get('typ')!r}")

    expected_sig = hmac.new(key, f"{h_b64}.{p_b64}".encode(), hashlib.sha256).digest()
    if not hmac.compare_digest(sig, expected_sig):
        raise JwtError("signature mismatch")

    if payload.get("iss") != EXPECTED_ISSUER:
        raise JwtError(f"unexpected iss {payload.get('iss')!r}")
    if payload.get("aud") != EXPECTED_AUDIENCE:
        raise JwtError(f"unexpected aud {payload.get('aud')!r}")

    sub = payload.get("sub")
    device_id = payload.get("device_id")
    jti = payload.get("jti")
    exp = payload.get("exp")
    if not isinstance(sub, str) or not sub:
        raise JwtError("missing sub claim")
    if not isinstance(device_id, str) or not device_id:
        raise JwtError("missing device_id claim")
    if not isinstance(jti, str) or not jti:
        raise JwtError("missing jti claim")
    if not isinstance(exp, int):
        raise JwtError("missing or non-integer exp claim")

    current = now if now is not None else int(time.time())
    if exp + leeway_seconds < current:
        raise JwtError(f"token expired (exp={exp}, now={current})")

    return AudioJwt(sub=sub, device_id=device_id, jti=jti, exp=exp)


# ── jti replay protection ─────────────────────────────────────────────


class JtiSet:
    """In-memory set of used JWT IDs.

    Process-local — a relay restart resets the set, which means a
    captured token survives at most one restart-window of replay
    (5 minutes by default).  Documented trade-off in ``docs/AUDIO.md``.

    Periodic GC drops jtis whose corresponding exp has passed so the
    set doesn't grow unbounded across long-running processes.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._jtis: dict[str, int] = {}  # jti → exp epoch seconds

    def claim(self, jti: str, exp: int) -> bool:
        """True on first use of *jti*, False on replay.  Records the
        exp so the GC can prune expired entries."""
        with self._lock:
            self._gc_locked()
            if jti in self._jtis:
                return False
            self._jtis[jti] = exp
            return True

    def size(self) -> int:
        with self._lock:
            return len(self._jtis)

    def _gc_locked(self) -> None:
        now = int(time.time())
        stale = [j for j, exp in self._jtis.items() if exp < now]
        for j in stale:
            self._jtis.pop(j, None)
